var albumsArray = [
    {
        album: "Show No Mercy",
        imagePath: "img/1983ShowNoMercy.jpg",
        artist: "Slayer",
        country: "Los Angeles, CA (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1983,
    },
    {
        album: "Kill 'Em All",
        imagePath: "img/1983KillEmAll.jpeg",
        artist: "Metallica",
        country: "San Francisco, CA (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1983,
    },
    {
        album: "Ride The Lightning",
        imagePath: "img/1984RideTheLightning.jpg",
        artist: "Metallica",
        country: "San Francisco, CA (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1984,
    },
    {
        album: "No Escape",
        imagePath: "img/1984NoEscape.jpg",
        artist: "Hexx",
        country: "San Francisco, CA (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1984,
    },
    {
        album: "Vengeance Of Hell",
        imagePath: "img/1984VengeanceOfHell.jpg",
        artist: "Living Death",
        country: "Velbert, West Germany",
        countryPath: "img/FlagGermany.png",
        year: 1984,
    },
    {
        album: "All Hail To Thee",
        imagePath: "img/1984AllHailToThee.jpeg",
        artist: "Znöwhite",
        country: "Chicago, IL (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1984,
    },
    {
        album: "Fistful Of Metal",
        imagePath: "img/1984FistfulOfMetal.jpg",
        artist: "Anthrax",
        country: "New York City, NY (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1984,
    },
    {
        album: "War And Pain",
        imagePath: "img/1984WarAndPain.jpg",
        artist: "Voivod",
        country: "Jonquière, Quebec (CAN)",
        countryPath: "img/FlagCanada.jpg",
        year: 1984,
    },
    {
        album: "Spreading The Disease",
        imagePath: "img/1985SpreadingTheDisease.jpg",
        artist: "Anthrax",
        country: "New York City, NY (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1985,
    },
    {
        album: "Dealing with It!",
        imagePath: "img/1985DealingWithIt.jpg",
        artist: "D.R.I.",
        country: "Houston, TX (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1985,
    },
    {
        album: "Metal Revolution",
        imagePath: "img/1985MetalRevolution.jpg",
        artist: "Living Death",
        country: "Velbert, West Germany",
        countryPath: "img/FlagGermany.png",
        year: 1985,
    },
    {
        album: "Seven Churches",
        imagePath: "img/1985SevenChurches.jpg",
        artist: "Possessed",
        country: "San Francisco, CA (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1985,
    },
    {
        album: "Endless Pain",
        imagePath: "img/1985EndlessPain.jpg",
        artist: "Kreator",
        country: "Essen, North Rhine-Westphalia, West Germany",
        countryPath: "img/FlagGermany.png",
        year: 1985,
    },
    {
        album: "Fear Of Tomorrow",
        imagePath: "img/1985FearOfTomorrow.jpg",
        artist: "Artillery",
        country: "Taastrup, Denmark",
        countryPath: "img/FlagDenmark.png",
        year: 1985,
    },
    {
        album: "Hell Awaits",
        imagePath: "img/1985HellAwaits.jpg",
        artist: "Slayer",
        country: "Los Angeles, CA (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1985,
    },
    {
        album: "Kill Or Be Killed",
        imagePath: "img/1985KillOrBeKilled.png",
        artist: "Blessed Death",
        country: "Old Bridge, NJ (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1985,
    },
    {
        album: "Vicious Attack",
        imagePath: "img/1985ViciousAttack.jpg",
        artist: "Abbatoir",
        country: "Los Angeles, CA (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1985,
    },
    {
        album: "Tales Of Terror",
        imagePath: "img/1985TalesOfTerror.jpg",
        artist: "Hallows Eve",
        country: "Atlanta, GA (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1985,
    },
    {
        album: "Bonded By Blood",
        imagePath: "img/1985BondedByBlood.jpg",
        artist: "Exodus",
        country: "Richmond, CA (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1985,
    },
    {
        album: "Power From Hell",
        imagePath: "img/1985PowerFromHell.jpg",
        artist: "Onslaught",
        country: "Bristol (England)",
        countryPath: "img/FlagEngland.png",
        year: 1985,
    },
    {
        album: "Infernal Overkill",
        imagePath: "img/1985InfernalOverkill.jpg",
        artist: "Destruction",
        country: "Weil am Rhein, West Germany",
        countryPath: "img/FlagGermany.png",
        year: 1985,
    },
    {
        album: "Feel The Fire",
        imagePath: "img/1985FeelTheFire.jpg",
        artist: "Overkill",
        country: "Old Bridge, NJ (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1985,
    },
    {
        album: "Skeptics Apocalypse",
        imagePath: "img/1985SkepticsApocalypse.jpg",
        artist: "Agent Steel",
        country: "Los Angeles, CA (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1985,
    },
    {
        album: "Evil Invaders",
        imagePath: "img/1985EvilInvaders.jpg",
        artist: "Razor",
        country: "Guelph, Ontario (CAN)",
        countryPath: "img/FlagCanada.jpg",
        year: 1985,
    },
    {
        album: "Executioner's Song",
        imagePath: "img/1985ExecutionersSong.jpg",
        artist: "Razor",
        country: "Guelph, Ontario (CAN)",
        countryPath: "img/FlagCanada.jpg",
        year: 1985,
    },
    {
        album: "Speak English Or Die",
        imagePath: "img/1985SpeakEnglishOrDie.jpg",
        artist: "S.O.D.",
        country: "New York City, NY (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1985,
    },
    {
        album: "Carnivore",
        imagePath: "img/1985Carnivore.jpg",
        artist: "Carnivore",
        country: "New York City, NY (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1985,
    },
    {
        album: "Raging Violence",
        imagePath: "img/1985RagingViolence.png",
        artist: "Hirax",
        country: "Buena Park, CA (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1985,
    },
    {
        album: "Killing Is My Business... And Business Is Good!",
        imagePath: "img/1985KillingIsMyBusiness.jpg",
        artist: "Megadeth",
        country: "Los Angeles, CA (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1985,
    },
    {
        album: "Peace Sells... But Who's Buying?",
        imagePath: "img/1986PeaceSells.jpg",
        artist: "Megadeth",
        country: "Los Angeles, CA (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1986,
    },
    {
        album: "Pleasure To Kill",
        imagePath: "img/1986PleasureToKill.jpg",
        artist: "Kreator",
        country: "Essen, North Rhine-Westphalia, West Germany",
        countryPath: "img/FlagGermany.png",
        year: 1986,
    },
    {
        album: "Eternal Devastation",
        imagePath: "img/1986EternalDevastation.jpg",
        artist: "Destruction",
        country: "Weil am Rhein, West Germany",
        countryPath: "img/FlagGermany.png",
        year: 1986,
    },
    {
        album: "The Force",
        imagePath: "img/1986TheForce.jpg",
        artist: "Onslaught",
        country: "Bristol (England)",
        countryPath: "img/FlagEngland.png",
        year: 1986,
    },
    {
        album: "Malicious Intent",
        imagePath: "img/1986MaliciousIntent.jpg",
        artist: "Razor",
        country: "Guelph, Ontario (CAN)",
        countryPath: "img/FlagCanada.jpg",
        year: 1986,
    },
    {
        album: "Morbid Visions",
        imagePath: "img/1986MorbidVisions.jpg",
        artist: "Sepultura",
        country: "Belo Horizonte, Brazil",
        countryPath: "img/FlagBrazil.jpg",
        year: 1986,
    },
    {
        album: "Hate, Fear And Power",
        imagePath: "img/1986HateFearAndPower.jpg",
        artist: "Hirax",
        country: "Buena Park, CA (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1986,
    },
    {
        album: "Death & Insanity",
        imagePath: "img/1986Death&Insanity.jpg",
        artist: "Hallows Eve",
        country: "Atlanta, GA (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1986,
    },
    {
        album: "The Only Safe Place",
        imagePath: "img/1986TheOnlySafePlace.jpg",
        artist: "Abbatoir",
        country: "Los Angeles, CA (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1986,
    },
    {
        album: "Torment In Fire",
        imagePath: "img/1986TormentInFire.jpg",
        artist: "Sacrifice",
        country: "Toronto, Ontario (CAN)",
        countryPath: "img/FlagCanada.jpg",
        year: 1986,
    },
    {
        album: "Master Of Puppets",
        imagePath: "img/1986MasterOfPuppets.jpg",
        artist: "Metallica",
        country: "San Francisco, CA (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1986,
    },
    {
        album: "Fit Of Anger",
        imagePath: "img/1986FitOfAnger.jpg",
        artist: "Wrath",
        country: "Chicago, IL (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1986,
    },
    {
        album: "Kawaleria Szatana",
        imagePath: "img/1986KawaleriaSzatana.jpg",
        artist: "Turbo",
        country: "Poznań, Poland",
        countryPath: "img/FlagPoland.jpg",
        year: 1986,
    },
    {
        album: "The Rules Have Been Disturbed",
        imagePath: "img/1986TheRulesHaveBeenDisturbed.jpg",
        artist: "Mysto Dysto",
        country: "Coevorden (Netherlands)",
        countryPath: "img/FlagNetherlands.png",
        year: 1986,
    },
    {
        album: "Darkness Descends",
        imagePath: "img/1986DarknessDescends.jpg",
        artist: "Dark Angel",
        country: "Downey, CA (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1986,
    },
    {
        album: "Reign In Blood",
        imagePath: "img/1986ReignInBlood.jpg",
        artist: "Slayer",
        country: "Los Angeles, CA (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1986,
    },
    {
        album: "666",
        imagePath: "img/1986666.png",
        artist: "Kat",
        country: "Katowice, Poland",
        countryPath: "img/FlagPoland.jpg",
        year: 1986,
    },
    {
        album: "Doomsday For The Deceiver",
        imagePath: "img/1986DoomsdayForTheDeceiver.jpg",
        artist: "Flotsam and Jetsam",
        country: "Phoenix, AZ (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1986,
    },
    {
        album: "Beyond The Gates",
        imagePath: "img/1986BeyondTheGates.jpg",
        artist: "Possessed",
        country: "San Francisco, CA (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1986,
    },
    {
        album: "Power And Pain",
        imagePath: "img/1986PowerAndPain.jpg",
        artist: "Whiplash",
        country: "Passaic, NJ (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1986,
    },
    {
        album: "Zombie Attack",
        imagePath: "img/1986ZombieAttack.jpg",
        artist: "Tankard",
        country: "Frankfurt, West Germany",
        countryPath: "img/FlagGermany.png",
        year: 1986,
    },
    {
        album: "Possessed By Fire",
        imagePath: "img/1986PossessedByFire.jpg",
        artist: "Exumer",
        country: "Wiesbaden, West Germany",
        countryPath: "img/FlagGermany.png",
        year: 1986,
    },
    {
        album: "Rrröööaaarrr",
        imagePath: "img/1986Rrroooaaarrr.jpg",
        artist: "Voivod",
        country: "Jonquière, Quebec (CAN)",
        countryPath: "img/FlagCanada.jpg",
        year: 1986,
    },
    {
        album: "Brutal Destruction",
        imagePath: "img/1986BrutalDestruction.jpg",
        artist: "Cyclone",
        country: "Vilvoorde, Belgium",
        countryPath: "img/FlagBelgium.png",
        year: 1986,
    },
    {
        album: "Game Over",
        imagePath: "img/1986GameOver.jpg",
        artist: "Nuclear Assault",
        country: "New York City, NY (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1986,
    },
    {
        album: "Life Of Dreams",
        imagePath: "img/1986LifeOfDreams.jpg",
        artist: "Crumbsuckers",
        country: "Long Island, NY (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1986,
    },
    {
        album: "Riders OF Doom",
        imagePath: "img/1986RidersOfDoom.jpg",
        artist: "Deathrow",
        country: "Düsseldorf, West Germany",
        countryPath: "img/FlagGermany.png",
        year: 1986,
    },
    {
        album: "Into The Dark Past",
        imagePath: "img/1986IntoTheDarkPast.jpg",
        artist: "Angel Dust",
        country: "Dortmund, West Germany",
        countryPath: "img/FlagGermany.png",
        year: 1986,
    },
    {
        album: "Under The Spell",
        imagePath: "img/1986UnderTheSpell.jpg",
        artist: "Hexx",
        country: "San Francisco, CA (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1986,
    },
    {
        album: "Rising From The Sea",
        imagePath: "img/1987RisingFromTheSea.jpg",
        artist: "Exumer",
        country: "Wiesbaden, West Germany",
        countryPath: "img/FlagGermany.png",
        year: 1987,
    },
    {
        album: "Raging Steel",
        imagePath: "img/1987RagingSteel.jpg",
        artist: "Deathrow",
        country: "Düsseldorf, West Germany",
        countryPath: "img/FlagGermany.png",
        year: 1987,
    },
    {
        album: "Persecution Mania",
        imagePath: "img/1987PersecutionMania.jpg",
        artist: "Sodom",
        country: "Gelsenkirchen, West Germany",
        countryPath: "img/FlagGermany.png",
        year: 1987,
    },
    {
        album: "Forward To Termination",
        imagePath: "img/1987ForwardToTermination.jpg",
        artist: "Sacrifice",
        country: "Toronto, Ontario (CAN)",
        countryPath: "img/FlagCanada.jpg",
        year: 1987,
    },
    {
        album: "The Upcoming Terror",
        imagePath: "img/1987TheUpcomingTerror.jpg",
        artist: "Assassin",
        country: "Düsseldorf, West Germany",
        countryPath: "img/FlagGermany.png",
        year: 1987,
    },
    {
        album: "Custom Killing",
        imagePath: "img/1987CustomKilling.jpg",
        artist: "Razor",
        country: "Guelph, Ontario (CAN)",
        countryPath: "img/FlagCanada.jpg",
        year: 1987,
    },
    {
        album: "Protected From Reality",
        imagePath: "img/1987ProtectedFromReality.jpg",
        artist: "Living Death",
        country: "Velbert, West Germany",
        countryPath: "img/FlagGermany.png",
        year: 1987,
    },
    {
        album: "Taking Over",
        imagePath: "img/1987TakingOver.jpg",
        artist: "Overkill",
        country: "Old Bridge, NJ (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1987,
    },
    {
        album: "...Conscience...",
        imagePath: "img/1987Conscience.jpg",
        artist: "Overdose",
        country: "Belo Horizonte, Brazil",
        countryPath: "img/FlagBrazil.jpg",
        year: 1987,
    },
    {
        album: "Pleasures Of The Flesh",
        imagePath: "img/1987PleasuresOfTheFlesh.jpg",
        artist: "Exodus",
        country: "Richmond, CA (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1987,
    },
    {
        album: "Chemical Invasion",
        imagePath: "img/1987ChemicalInvasion.jpg",
        artist: "Tankard",
        country: "Frankfurt, West Germany",
        countryPath: "img/FlagGermany.png",
        year: 1987,
    },
    {
        album: "Terror Squad",
        imagePath: "img/1987TerrorSquad.jpg",
        artist: "Artillery",
        country: "Taastrup, Denmark",
        countryPath: "img/FlagDenmark.png",
        year: 1987,
    },
    {
        album: "The Ultra-Violence",
        imagePath: "img/1987TheUltraViolence.jpg",
        artist: "Death Angel",
        country: "Daly City, CA (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1987,
    },
    {
        album: "Dead Brain Cells",
        imagePath: "img/1987DeadBrainCells.jpg",
        artist: "DBC",
        country: "Montréal, Quebec (CAN)",
        countryPath: "img/FlagCanada.jpg",
        year: 1987,
    },
    {
        album: "The Full Treatment",
        imagePath: "img/1987TheFullTreatment.jpg",
        artist: "Aggression",
        country: "Montréal, Quebec (CAN)",
        countryPath: "img/FlagCanada.jpg",
        year: 1987,
    },
    {
        album: "Destined For Extinction",
        imagePath: "img/1987DestinedForExtinction.jpg",
        artist: "Blessed Death",
        country: "Old Bridge, NJ (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1987,
    },
    {
        album: "Breaking The Silence",
        imagePath: "img/1987BreakingTheSilence.jpg",
        artist: "Heathen",
        country: "Sonora, CA (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1987,
    },
    {
        album: "Pray For War",
        imagePath: "img/1987PrayForWar.jpg",
        artist: "Virus",
        country: "Brighton (England)",
        countryPath: "img/FlagEngland.png",
        year: 1987,
    },
    {
        album: "Killing Technology",
        imagePath: "img/1987KillingTechnology.jpg",
        artist: "Voivod",
        country: "Jonquière, Quebec (CAN)",
        countryPath: "img/FlagCanada.jpg",
        year: 1987,
    },
    {
        album: "Crossover",
        imagePath: "img/1987Crossover.jpg",
        artist: "D.R.I.",
        country: "Houston, TX (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1987,
    },
    {
        album: "Schizophrenia",
        imagePath: "img/1987Schizophrenia.png",
        artist: "Sepultura",
        country: "Belo Horizonte, Brazil",
        countryPath: "img/FlagBrazil.jpg",
        year: 1987,
    },
    {
        album: "Ostatni Wojownik",
        imagePath: "img/1987OstatniWojownik.jpg",
        artist: "Turbo",
        country: "Poznań, Poland",
        countryPath: "img/FlagPoland.jpg",
        year: 1987,
    },
    {
        album: "Nothing To Fear",
        imagePath: "img/1987NothingToFear.jpg",
        artist: "Wrath",
        country: "Chicago, IL (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1987,
    },
    {
        album: "Among The Living",
        imagePath: "img/1987AmongTheLiving.jpg",
        artist: "Anthrax",
        country: "New York City, NY (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1987,
    },
    {
        album: "The Legacy",
        imagePath: "img/1987TheLegacy.jpg",
        artist: "Testament",
        country: "Berkeley, CA (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1987,
    },
    {
        album: "Split Image",
        imagePath: "img/1987SplitImage.jpg",
        artist: "Excel",
        country: "Venice, CA (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1987,
    },
    {
        album: "Know Your Enemy",
        imagePath: "img/1987KnowYourEnemy.jpg",
        artist: "Lȧȧz Rockit",
        country: "Oakland, CA (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1987,
    },
    {
        album: "World Circus",
        imagePath: "img/1987WorldCircus.jpg",
        artist: "Toxik",
        country: "Peekskill, NY (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1987,
    },
    {
        album: "Ignorance",
        imagePath: "img/1987Ignorance.jpg",
        artist: "Sacred Reich",
        country: "Phoenix, AZ (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1987,
    },
    {
        album: "Unstoppable Force",
        imagePath: "img/1987UnstoppableForce.jpg",
        artist: "Agent Steel",
        country: "Los Angeles, CA (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1987,
    },
    {
        album: "Terror And Submission",
        imagePath: "img/1987TerrorAndSubmission.jpg",
        artist: "Holy Terror",
        country: "Los Angeles, CA (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1987,
    },
    {
        album: "Total Armageddon",
        imagePath: "img/1987TotalArmageddon.jpg",
        artist: "Renegade",
        country: "Melbourne, Australia",
        countryPath: "img/FlagAustralia.jpg",
        year: 1987,
    },
    {
        album: "Strappado",
        imagePath: "img/1987Strappado.jpg",
        artist: "Slaughter",
        country: "Toronto, Ontario (CAN)",
        countryPath: "img/FlagCanada.jpg",
        year: 1987,
    },
    {
        album: "None Shall Defy",
        imagePath: "img/1987NoneShallDefy.jpg",
        artist: "Infernäl Mäjesty",
        country: "Toronto, Ontario (CAN)",
        countryPath: "img/FlagCanada.jpg",
        year: 1987,
    },
    {
        album: "Terrible Certainty",
        imagePath: "img/1987TerribleCertainty.jpg",
        artist: "Kreator",
        country: "Essen, North Rhine-Westphalia, West Germany",
        countryPath: "img/FlagGermany.png",
        year: 1987,
    },
    {
        album: "Wilczy Pająk",
        imagePath: "img/1987WilczyPajak.png",
        artist: "Wolf Spider",
        country: "Łódź, Poland",
        countryPath: "img/FlagPoland.jpg",
        year: 1987,
    },
    {
        album: "Mission Executed",
        imagePath: "img/1987MissionExecuted.jpg",
        artist: "Target",
        country: "Aalst, Belgium",
        countryPath: "img/FlagBelgium.png",
        year: 1987,
    },
    {
        album: "Ticket To Mayhem",
        imagePath: "img/1987TicketToMayhem.jpg",
        artist: "Whiplash",
        country: "Passaic, NJ (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1987,
    },
    {
        album: "Resisting Success",
        imagePath: "img/1987ResistingSuccess.jpg",
        artist: "Hades",
        country: "Paramus, NJ (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1987,
    },
    {
        album: "Go And Live... Stay And Die",
        imagePath: "img/1987GoAndLiveStayAndDie.jpg",
        artist: "Vendetta",
        country: "Schweinfurt, West Germany",
        countryPath: "img/FlagGermany.png",
        year: 1987,
    },
    {
        album: "Shark Attack",
        imagePath: "img/1987SharkAttack.jpg",
        artist: "Wehrmacht",
        country: "Portland, OR (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1987,
    },
    {
        album: "Mayhemic Destruction",
        imagePath: "img/1987MayhemicDestruction.jpg",
        artist: "Mortal Sin",
        country: "Sydney, Australia",
        countryPath: "img/FlagAustralia.jpg",
        year: 1987,
    },
    {
        album: "Death Squad",
        imagePath: "img/1987DeathSquad.jpg",
        artist: "Darkness",
        country: "Essen, West Germany",
        countryPath: "img/FlagGermany.png",
        year: 1987,
    },
    {
        album: "R.I.P.",
        imagePath: "img/1987RIP.jpg",
        artist: "Coroner",
        country: "Zürich, Switzerland",
        countryPath: "img/FlagSwitzerland.png",
        year: 1987,
    },
    {
        album: "Razorback",
        imagePath: "img/1987Razorback.jpg",
        artist: "I.N.C.",
        country: "Bridgeport, CT (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1987,
    },
    {
        album: "Retaliation",
        imagePath: "img/1987Retaliation.jpg",
        artist: "Carnivore",
        country: "New York City, NY (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1987,
    },
    {
        album: "Product Of Imagination",
        imagePath: "img/1987ProductOfImagination.jpg",
        artist: "Paradox",
        country: "Würzburg, West Germany",
        countryPath: "img/FlagGermany.png",
        year: 1987,
    },
    {
        album: "At The Edge Of Damnation",
        imagePath: "img/1987AtTheEdgeOfDamnation.jpg",
        artist: "Deathwish",
        country: "Brighton, East Sussex (England)",
        countryPath: "img/FlagEngland.png",
        year: 1987,
    },
    {
        album: "Demon Preacher",
        imagePath: "img/1988DemonPreacher.jpg",
        artist: "Deathwish",
        country: "Brighton, East Sussex (England)",
        countryPath: "img/FlagEngland.png",
        year: 1988,
    },
    {
        album: "The Visitor",
        imagePath: "img/1988TheVisitor.jpg",
        artist: "I.N.C.",
        country: "Bridgeport, CT (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1988,
    },
    {
        album: "A Tribute To Insanity",
        imagePath: "img/1988ATributeToInsanity.jpg",
        artist: "Hexenhaus",
        country: "Stockholm, Sweden",
        countryPath: "img/FlagSweden.png",
        year: 1988,
    },
    {
        album: "If At First You Don't Succeed",
        imagePath: "img/1988IfAtFirstYouDontSucceed.jpg",
        artist: "Hades",
        country: "Paramus, NJ (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1988,
    },
    {
        album: "Force Recon",
        imagePath: "img/1988ForceRecon.jpg",
        artist: "Virus",
        country: "Brighton (England)",
        countryPath: "img/FlagEngland.png",
        year: 1988,
    },
    {
        album: "Mind Wars",
        imagePath: "img/1988MindWars.jpg",
        artist: "Holy Terror",
        country: "Los Angeles, CA (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1988,
    },
    {
        album: "History Of A Time To Come",
        imagePath: "img/1988HistoryOfATimeToCome.jpg",
        artist: "Sabbat",
        country: "Nottingham (England)",
        countryPath: "img/FlagEngland.png",
        year: 1988,
    },
    {
        album: "Stone",
        imagePath: "img/1988Stone.jpg",
        artist: "Stone",
        country: "Kerava (Finland)",
        countryPath: "img/FlagFinland.png",
        year: 1988,
    },
    {
        album: "Brain Damage",
        imagePath: "img/1988BrainDamage.jpg",
        artist: "Vendetta",
        country: "Schweinfurt, West Germany",
        countryPath: "img/FlagGermany.png",
        year: 1988,
    },
    {
        album: "Dawn For The Living",
        imagePath: "img/1988DawnForTheLiving.jpg",
        artist: "Grinder",
        country: "Frankfurt, West Germany",
        countryPath: "img/FlagGermany.png",
        year: 1988,
    },
    {
        album: "Frolic Through The Park",
        imagePath: "img/1988FrolicThroughThePark.jpg",
        artist: "Death Angel",
        country: "Daly City, CA (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1988,
    },
    {
        album: "Eternal Nightmare",
        imagePath: "img/1988EternalNightmare.jpg",
        artist: "Vio-lence",
        country: "San Francisco, CA (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1988,
    },
    {
        album: "Oddech Wymarłych Światów",
        imagePath: "img/1988OddechWymarlychSwiatow.jpg",
        artist: "Kat",
        country: "Katowice, Poland",
        countryPath: "img/FlagPoland.jpg",
        year: 1988,
    },
    {
        album: "Violent Restitution",
        imagePath: "img/1988ViolentRestitution.jpg",
        artist: "Razor",
        country: "Guelph, Ontario (CAN)",
        countryPath: "img/FlagCanada.jpg",
        year: 1988,
    },
    {
        album: "Survive",
        imagePath: "img/1988Survive.jpg",
        artist: "Nuclear Assault",
        country: "New York City, NY (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1988,
    },
    {
        album: "State Of Euphoria",
        imagePath: "img/1988StateOfEuphoria.jpg",
        artist: "Anthrax",
        country: "New York City, NY (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1988,
    },
    {
        album: "The New Order",
        imagePath: "img/1988TheNewOrder.jpg",
        artist: "Testament",
        country: "Berkeley, CA (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1988,
    },
    {
        album: "Say Uncle",
        imagePath: "img/1988SayUncle.jpg",
        artist: "Unlce Slam",
        country: "Beverly Hills, CA (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1988,
    },
    {
        album: "Beast On My Back",
        imagePath: "img/1988BeastOnMyBack.jpg",
        artist: "Crumbsuckers",
        country: "Long Island, NY (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1988,
    },
    {
        album: "Dimension Hatröss",
        imagePath: "img/1988DimensionHatross.jpg",
        artist: "Voivod",
        country: "Jonquière, Quebec (CAN)",
        countryPath: "img/FlagCanada.jpg",
        year: 1988,
    },
    {
        album: "Act Of God",
        imagePath: "img/1988ActOfGod.jpg",
        artist: "Znöwhite",
        country: "Chicago, IL (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1988,
    },
    {
        album: "Initial Velocity",
        imagePath: "img/1988InitialVelocity.jpg",
        artist: "Mandator",
        country: "Coevorden (Netherlands)",
        countryPath: "img/FlagNetherlands.png",
        year: 1988,
    },
    {
        album: "So Far, So Good... So What!",
        imagePath: "img/1988SoFarSoGoodSoWhat.jpg",
        artist: "Megadeth",
        country: "Los Angeles, CA (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1988,
    },
    {
        album: "Rather Death Than False Of Faith",
        imagePath: "img/1988RatherDeathThanFalseOfFaith.png",
        artist: "Hydra Vein",
        country: "Brighton (England)",
        countryPath: "img/FlagEngland.png",
        year: 1988,
    },
    {
        album: "The Morning After",
        imagePath: "img/1988TheMorningAfter.jpg",
        artist: "Tankard",
        country: "Frankfurt, West Germany",
        countryPath: "img/FlagGermany.png",
        year: 1988,
    },
    {
        album: "Golem",
        imagePath: "img/1988Golem.jpg",
        artist: "Protector",
        country: "Wolfsburg, West Germany",
        countryPath: "img/FlagGermany.png",
        year: 1988,
    },
    {
        album: "Ritually Abused",
        imagePath: "img/1988RituallyAbused.jpg",
        artist: "Num Skull",
        country: "Winthrop Harbor, IL (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1988,
    },
    {
        album: "The Daily Horror News",
        imagePath: "img/1988TheDailyHorrorNews.jpg",
        artist: "Risk",
        country: "Witten, West Germany",
        countryPath: "img/FlagGermany.png",
        year: 1988,
    },
    {
        album: "...And Justice For All",
        imagePath: "img/1988AndJusticeForAll.jpg",
        artist: "Metallica",
        country: "San Francisco, CA (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1988,
    },
    {
        album: "South Of Heaven",
        imagePath: "img/1988SouthOfHeaven.jpg",
        artist: "Slayer",
        country: "Los Angeles, CA (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1988,
    },
    {
        album: "To Dust You Will Decay",
        imagePath: "img/1988ToDustYouWillDecay.jpg",
        artist: "Angel Dust",
        country: "Dortmund, West Germany",
        countryPath: "img/FlagGermany.png",
        year: 1988,
    },
    {
        album: "Socialized Hate",
        imagePath: "img/1988SocializedHate.jpg",
        artist: "Atrophy",
        country: "Tucson, AZ (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1988,
    },
    {
        album: "Rigor Mortis",
        imagePath: "img/1988RigorMortis.jpg",
        artist: "Rigor Mortis",
        country: "Dallas-Ft. Worth, TX (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1988,
    },
    {
        album: "Hell House",
        imagePath: "img/1988HellHouse.jpg",
        artist: "Holosade",
        country: "Darlington, (England)",
        countryPath: "img/FlagEngland.png",
        year: 1988,
    },
    {
        album: "The Kindred",
        imagePath: "img/1988TheKindred.jpg",
        artist: "Pariah",
        country: "Newcastle (England)",
        countryPath: "img/FlagEngland.png",
        year: 1988,
    },
    {
        album: "Interstellar Experience",
        imagePath: "img/1988InterstellarExperience.jpg",
        artist: "Assassin",
        country: "Düsseldorf, West Germany",
        countryPath: "img/FlagGermany.png",
        year: 1988,
    },
    {
        album: "Punishment For Decadence",
        imagePath: "img/1988PunishmentForDecadence.jpg",
        artist: "Coroner",
        country: "Zürich, Switzerland",
        countryPath: "img/FlagSwitzerland.png",
        year: 1988,
    },
    {
        album: "Defenders Of Justice",
        imagePath: "img/1988DefendersOfJustice.jpg",
        artist: "Darkness",
        country: "Essen, West Germany",
        countryPath: "img/FlagGermany.png",
        year: 1988,
    },
    {
        album: "Release From Agony",
        imagePath: "img/1988ReleaseFromAgony.jpg",
        artist: "Destruction",
        country: "Weil am Rhein, West Germany",
        countryPath: "img/FlagGermany.png",
        year: 1988,
    },
    {
        album: "Change From Reality",
        imagePath: "img/1988ChangeFromReality.jpg",
        artist: "Toxic Shock",
        country: "Eislingen, West Germany",
        countryPath: "img/FlagGermany.png",
        year: 1988,
    },
    {
        album: "Lifecycle",
        imagePath: "img/1988Lifecycle.jpg",
        artist: "Sieges Even",
        country: "Munich, West Germany",
        countryPath: "img/FlagGermany.png",
        year: 1988,
    },
    {
        album: "Refuge Denied",
        imagePath: "img/1988RefugeDenied.jpg",
        artist: "Sanctuary",
        country: "Seattle, WA (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1988,
    },
    {
        album: "Black Clouds",
        imagePath: "img/1988BlackClouds.jpg",
        artist: "Outrage",
        country: "Nagoya, Japan",
        countryPath: "img/FlagJapan.jpg",
        year: 1988,
    },
    {
        album: "Endless War",
        imagePath: "img/1988EndlessWar.jpg",
        artist: "Realm",
        country: "Milwaukee, WI (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1988,
    },
    {
        album: "4 Of A Kind",
        imagePath: "img/19884OfAKind.jpg",
        artist: "D.R.I.",
        country: "Houston, TX (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1988,
    },
    {
        album: "No Place For Disgrace",
        imagePath: "img/1988NoPlaceForDisgrace.jpg",
        artist: "Flotsam and Jetsam",
        country: "Phoenix, AZ (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1988,
    },
    {
        album: "Monument",
        imagePath: "img/1988Monument.jpg",
        artist: "Hallows Eve",
        country: "Atlanta, GA (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1988,
    },
    {
        album: "Under The Influence",
        imagePath: "img/1988UnderTheInfluence.jpg",
        artist: "Overkill",
        country: "Old Bridge, NJ (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1988,
    },
    {
        album: "Killer Instinct",
        imagePath: "img/1988KillerInstinct.jpg",
        artist: "Gothic Slam",
        country: "Jersey City, NJ (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1988,
    },
    {
        album: "Forbidden Evil",
        imagePath: "img/1988ForbiddenEvil.jpg",
        artist: "Forbidden",
        country: "Hayward, CA (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1988,
    },
    {
        album: "Why Play Around?",
        imagePath: "img/1988WhyPlayAround.jpg",
        artist: "Wargasm",
        country: "Boston, MA (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1988,
    },
    {
        album: "Angel Of Death",
        imagePath: "img/1988AngelOfDeath.jpg",
        artist: "Hobbs' Angel of Death",
        country: "Melbourne, Australia",
        countryPath: "img/FlagAustralia.jpg",
        year: 1988,
    },
    {
        album: "Do Or Die",
        imagePath: "img/1988DoOrDie.jpg",
        artist: "Viking",
        country: "Los Angeles, CA (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1988,
    },
    {
        album: "Power Of Darkness",
        imagePath: "img/1988PowerOfDarkness.jpg",
        artist: "Minotaur",
        country: "Halstenbeck, West Germany",
        countryPath: "img/FlagGermany.png",
        year: 1988,
    },
    {
        album: "Prey",
        imagePath: "img/1989Prey.jpg",
        artist: "Loss For Words",
        country: "Elmira, NY (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1989,
    },
    {
        album: "Man Of Straw",
        imagePath: "img/1989ManOfStraw.jpg",
        artist: "Viking",
        country: "Los Angeles, CA (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1989,
    },
    {
        album: "Alice In Hell",
        imagePath: "img/1989AliceInHell.jpg",
        artist: "Annihilator",
        country: "Ottawa, Ontario (CAN)",
        countryPath: "img/FlagCanada.jpg",
        year: 1989,
    },
    {
        album: "Face Of Despair",
        imagePath: "img/1989FaceOfDespair.png",
        artist: "Mortal Sin",
        country: "Sydney, Australia",
        countryPath: "img/FlagAustralia.jpg",
        year: 1989,
    },
    {
        album: "Perfect Progeny",
        imagePath: "img/1989PerfectProgeny.jpg",
        artist: "Mandator",
        country: "Coevorden (Netherlands)",
        countryPath: "img/FlagNetherlands.png",
        year: 1989,
    },
    {
        album: "Lost In Wonderland",
        imagePath: "img/1989LostInWonderland.jpg",
        artist: "Nuclear Simphony",
        country: "Favara, Italy",
        countryPath: "img/FlagItaly.png",
        year: 1989,
    },
    {
        album: "The Years Of Decay",
        imagePath: "img/1989TheYearsOfDecay.jpg",
        artist: "Overkill",
        country: "Old Bridge, NJ (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1989,
    },
    {
        album: "No Anaesthesia!",
        imagePath: "img/1989NoAnaesthesia.jpg",
        artist: "Stone",
        country: "Kerava (Finland)",
        countryPath: "img/FlagFinland.png",
        year: 1989,
    },
    {
        album: "Beware",
        imagePath: "img/1989Beware.jpg",
        artist: "Shah",
        country: "Moscow, Russia",
        countryPath: "img/FlagRussia.png",
        year: 1989,
    },
    {
        album: "Deception Ignored",
        imagePath: "img/1989DeceptionIgnored.jpg",
        artist: "Deathrow",
        country: "Düsseldorf, West Germany",
        countryPath: "img/FlagGermany.png",
        year: 1989,
    },
    {
        album: "The Joke's On You",
        imagePath: "img/1989TheJokesOnYou.jpg",
        artist: "Excel",
        country: "Venice, CA (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1989,
    },
    {
        album: "Dead End",
        imagePath: "img/1989DeadEnd.jpg",
        artist: "Grinder",
        country: "Frankfurt, West Germany",
        countryPath: "img/FlagGermany.png",
        year: 1989,
    },
    {
        album: "Dreamweaver",
        imagePath: "img/1989Dreamweaver.jpg",
        artist: "Sabbat",
        country: "Nottingham (England)",
        countryPath: "img/FlagEngland.png",
        year: 1989,
    },
    {
        album: "Human Wreckage",
        imagePath: "img/1989HumanWreckage.jpg",
        artist: "D.A.M.",
        country: "Morecambe, Lancashire (England)",
        countryPath: "img/FlagEngland.png",
        year: 1989,
    },
    {
        album: "Blaze Of Obscurity",
        imagePath: "img/1989BlazeOfObscurity.jpg",
        artist: "Pariah",
        country: "Newcastle (England)",
        countryPath: "img/FlagEngland.png",
        year: 1989,
    },
    {
        album: "After The Dream",
        imagePath: "img/1989AfterTheDream.jpg",
        artist: "Hydra Vein",
        country: "Brighton (England)",
        countryPath: "img/FlagEngland.png",
        year: 1989,
    },
    {
        album: "Signs Of Life",
        imagePath: "img/1989SignsOfLife.jpg",
        artist: "Devastation",
        country: "Corpus Christi, TX (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1989,
    },
    {
        album: "Fabulous Disaster",
        imagePath: "img/1989FabulousDisaster.jpg",
        artist: "Exodus",
        country: "Richmond, CA (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1989,
    },
    {
        album: "Lunacy",
        imagePath: "img/1989Lunacy.jpg",
        artist: "Virus",
        country: "Brighton (England)",
        countryPath: "img/FlagEngland.png",
        year: 1989,
    },
    {
        album: "Pity Of Man",
        imagePath: "img/1989PityOfMan.jpg",
        artist: "Addictive",
        country: "Sydney, Australia",
        countryPath: "img/FlagAustralia.jpg",
        year: 1989,
    },
    {
        album: "Practice What You Preach",
        imagePath: "img/1989PracticeWhatYouPreach.jpg",
        artist: "Testament",
        country: "Berkeley, CA (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1989,
    },
    {
        album: "In Search Of Sanity",
        imagePath: "img/1989InSearchOfSanity.jpg",
        artist: "Onslaught",
        country: "Bristol (England)",
        countryPath: "img/FlagEngland.png",
        year: 1989,
    },
    {
        album: "Nothingface",
        imagePath: "img/1989Nothingface.jpg",
        artist: "Voivod",
        country: "Jonquière, Quebec (CAN)",
        countryPath: "img/FlagCanada.jpg",
        year: 1989,
    },
    {
        album: "Handle With Care",
        imagePath: "img/1989HandleWithCare.jpg",
        artist: "Nuclear Assault",
        country: "New York City, NY (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1989,
    },
    {
        album: "Worlds Neuroses",
        imagePath: "img/1989WorldsNeuroses.jpg",
        artist: "Living Death",
        country: "Velbert, West Germany",
        countryPath: "img/FlagGermany.png",
        year: 1989,
    },
    {
        album: "Hell's Animals",
        imagePath: "img/1989HellsAnimals.jpg",
        artist: "Risk",
        country: "Witten, West Germany",
        countryPath: "img/FlagGermany.png",
        year: 1989,
    },
    {
        album: "Annihilation Principle",
        imagePath: "img/1989AnnihilationPrinciple.jpg",
        artist: "Lȧȧz Rockit",
        country: "Oakland, CA (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1989,
    },
    {
        album: "Epidemie",
        imagePath: "img/1989Epidemie.jpg",
        artist: "Turbo",
        country: "Poznań, Poland",
        countryPath: "img/FlagPoland.jpg",
        year: 1989,
    },
    {
        album: "Just A Face In The Crowd",
        imagePath: "img/1989JustAFaceInTheCrowd.jpg",
        artist: "Gothic Slam",
        country: "Jersey City, NJ (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1989,
    },
    {
        album: "No More Color",
        imagePath: "img/1989NoMoreColor.jpg",
        artist: "Coroner",
        country: "Zürich, Switzerland",
        countryPath: "img/FlagSwitzerland.png",
        year: 1989,
    },
    {
        album: "Think This",
        imagePath: "img/1989ThinkThis.jpg",
        artist: "Toxik",
        country: "Peekskill, NY (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1989,
    },
    {
        album: "Climbin' The Walls",
        imagePath: "img/1989ClimbinTheWalls.jpg",
        artist: "Wrathchild America",
        country: "Baltimore, MD (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1989,
    },
    {
        album: "Thrash Zone",
        imagePath: "img/1989ThrashZone.jpg",
        artist: "D.R.I.",
        country: "Houston, TX (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1989,
    },
    {
        album: "Product Of Society",
        imagePath: "img/1989ProductOfSociety.jpg",
        artist: "Defiance",
        country: "Oakland, CA (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1989,
    },
    {
        album: "Human Hell",
        imagePath: "img/1989HumanHell.jpg",
        artist: "Harter Attack",
        country: "Waterford Works, NJ (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1989,
    },
    {
        album: "Punishment Area",
        imagePath: "img/1989PunishmentArea.jpg",
        artist: "Faith or Fear",
        country: "Philadelphia, PA (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1989,
    },
    {
        album: "The New Machine Of Liechtenstein",
        imagePath: "img/1989TheNewMachineOfLiechtenstein.png",
        artist: "Holy Moses",
        country: "Aachen, West Germany",
        countryPath: "img/FlagGermany.png",
        year: 1989,
    },
    {
        album: "Heresey",
        imagePath: "img/1989Heresey.jpg",
        artist: "Paradox",
        country: "Würzburg, West Germany",
        countryPath: "img/FlagGermany.png",
        year: 1989,
    },
    {
        album: "Extreme Aggression",
        imagePath: "img/1989ExtremeAggression.jpg",
        artist: "Kreator",
        country: "Essen, North Rhine-Westphalia, West Germany",
        countryPath: "img/FlagGermany.png",
        year: 1989,
    },
    {
        album: "Beneath The Remains",
        imagePath: "img/1989BeneathTheRemains.jpg",
        artist: "Sepultura",
        country: "Belo Horizonte, Brazil",
        countryPath: "img/FlagBrazil.jpg",
        year: 1989,
    },
    {
        album: "You're Really Big!",
        imagePath: "img/1989YoureReallyBig.jpg",
        artist: "Overdose",
        country: "Belo Horizonte, Brazil",
        countryPath: "img/FlagBrazil.jpg",
        year: 1989,
    },
    {
        album: "Agent Orange",
        imagePath: "img/1989AgentOrange.jpg",
        artist: "Sodom",
        country: "Gelsenkirchen, West Germany",
        countryPath: "img/FlagGermany.png",
        year: 1989,
    },
    {
        album: "Depression",
        imagePath: "img/1989Depression.jpg",
        artist: "Poltergeist",
        country: "Liestal, Switzerland",
        countryPath: "img/FlagSwitzerland.png",
        year: 1989,
    },
    {
        album: "Master Project Genesis",
        imagePath: "img/1989MasterProjectGenesis.jpg",
        artist: "Target",
        country: "Aalst, Belgium",
        countryPath: "img/FlagBelgium.png",
        year: 1989,
    },
    {
        album: "Annihilation Of Civilization",
        imagePath: "img/1989AnnihilationOfCivilization.jpg",
        artist: "Evildead",
        country: "Los Angeles, CA (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1989,
    },
    {
        album: "A Higher Form Of Killing",
        imagePath: "img/1989AHigherFormOfKilling.jpg",
        artist: "Intruder",
        country: "Nashville, TN (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1989,
    },
    {
        album: "Leave Scars",
        imagePath: "img/1989LeaveScars.jpg",
        artist: "Dark Angel",
        country: "Downey, CA (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1989,
    },
    {
        album: "Insult To Injury",
        imagePath: "img/1989InsultToInjury.jpg",
        artist: "Whiplash",
        country: "Passaic, NJ (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1989,
    },
    {
        album: "Victims Of Science",
        imagePath: "img/1989VictimsOfScience.jpg",
        artist: "Gammacide",
        country: "Arlington, TX (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1989,
    },
    {
        album: "Universe",
        imagePath: "img/1989Universe.jpg",
        artist: "DBC",
        country: "Montréal, Quebec (CAN)",
        countryPath: "img/FlagCanada.jpg",
        year: 1989,
    },
    {
        album: "Control And Resistance",
        imagePath: "img/1989ControlAndResistance.jpg",
        artist: "Watchtower",
        country: "Austin, TX (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1989,
    },
    {
        album: "Fool's Game",
        imagePath: "img/1989FoolsGame.jpg",
        artist: "Mordred",
        country: "San Francisco, CA (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1989,
    },
    {
        album: "Absolute Power",
        imagePath: "img/1989AbsolutePower.jpg",
        artist: "Powermad",
        country: "Minneapolis, MN (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1989,
    },
    {
        album: "Limits Of Insanity",
        imagePath: "img/1989LimitsOfInsanity.jpg",
        artist: "Attomica",
        country: "São José dos Campos, Brazil",
        countryPath: "img/FlagBrazil.jpg",
        year: 1989,
    },
    {
        album: "Shattered Existence",
        imagePath: "img/1989ShatteredExistence.jpg",
        artist: "Xentrix",
        country: "Preston, Lancashire (England)",
        countryPath: "img/FlagEngland.png",
        year: 1989,
    },
    {
        album: "The Fear",
        imagePath: "img/1989TheFear.jpeg",
        artist: "Acid Reign",
        country: "Harrogate, Yorkshire (England)",
        countryPath: "img/FlagEngland.png",
        year: 1989,
    },
    {
        album: "The Work Of Idle Hands...",
        imagePath: "img/1989TheWorkOfIdleHands.jpg",
        artist: "Slammer",
        country: "Bradford (England)",
        countryPath: "img/FlagEngland.png",
        year: 1989,
    },
    {
        album: "Violent By Nature",
        imagePath: "img/1990ViolentByNature.jpg",
        artist: "Atrophy",
        country: "Tucson, AZ (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1990,
    },
    {
        album: "Welcome Home... Near Dark",
        imagePath: "img/1990WelcomeHomeNearDark.jpg",
        artist: "Toxic Shock",
        country: "Eislingen, West Germany",
        countryPath: "img/FlagGermany.png",
        year: 1990,
    },
    {
        album: "Mirror, My Mirror",
        imagePath: "img/1990MirrorMyMirror.jpg",
        artist: "Witchhammer",
        country: "Belo Horizonte, Brazil",
        countryPath: "img/FlagBrazil.jpg",
        year: 1990,
    },
    {
        album: "Kingdom Of Paranoia",
        imagePath: "img/1990KingdomOfParanoia.jpg",
        artist: "Wolf Spider",
        country: "Łódź, Poland",
        countryPath: "img/FlagPoland.jpg",
        year: 1990,
    },
    {
        album: "Shotgun Justice",
        imagePath: "img/1990ShotgunJustice.jpg",
        artist: "Razor",
        country: "Guelph, Ontario (CAN)",
        countryPath: "img/FlagCanada.jpg",
        year: 1990,
    },
    {
        album: "Fatal Games",
        imagePath: "img/1990FatalGames.jpg",
        artist: "Vulture",
        country: "Rotterdam (Netherlands)",
        countryPath: "img/FlagNetherlands.png",
        year: 1990,
    },
    {
        album: "Obnoxious",
        imagePath: "img/1990Obnoxious.jpg",
        artist: "Acid Reign",
        country: "Harrogate, Yorkshire (England)",
        countryPath: "img/FlagEngland.png",
        year: 1990,
    },
    {
        album: "Into The Mirror Black",
        imagePath: "img/1990IntoTheMirrorBlack.jpg",
        artist: "Sanctuary",
        country: "Seattle, WA (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1990,
    },
    {
        album: "World Won't Miss You",
        imagePath: "img/1990WorldWontMissYou.jpg",
        artist: "Reverend",
        country: "Seattle, WA (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1990,
    },
    {
        album: "Terrortory",
        imagePath: "img/1990Terrortory.jpg",
        artist: "Messina",
        country: "Heesch (Netherlands)",
        countryPath: "img/FlagNetherlands.png",
        year: 1990,
    },
    {
        album: "Beg To Differ",
        imagePath: "img/1990BegToDiffer.jpg",
        artist: "Prong",
        country: "New York City, NY (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1990,
    },
    {
        album: "Harsh Realities",
        imagePath: "img/1990HarshRealities.jpg",
        artist: "Bitter End",
        country: "Seattle, WA (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1990,
    },
    {
        album: "Dead End",
        imagePath: "img/1990DeadEnd.jpg",
        artist: "Turbo",
        country: "Poznań, Poland",
        countryPath: "img/FlagPoland.jpg",
        year: 1990,
    },
    {
        album: "Never, Neverland",
        imagePath: "img/1990NeverNeverland.jpg",
        artist: "Annihilator",
        country: "Ottawa, Ontario (CAN)",
        countryPath: "img/FlagCanada.jpg",
        year: 1990,
    },
    {
        album: "Colours",
        imagePath: "img/1990Colours.jpg",
        artist: "Stone",
        country: "Kerava (Finland)",
        countryPath: "img/FlagFinland.png",
        year: 1990,
    },
    {
        album: "The Edge Of Eternity",
        imagePath: "img/1990TheEdgeOfEternity.jpg",
        artist: "Hexenhaus",
        country: "Stockholm, Sweden",
        countryPath: "img/FlagSweden.png",
        year: 1990,
    },
    {
        album: "An Act Of Violence",
        imagePath: "img/1990AnActOfViolence.jpg",
        artist: "Moral Crusade",
        country: "Dublin, Ireland",
        countryPath: "img/FlagIreland.png",
        year: 1990,
    },
    {
        album: "Act III",
        imagePath: "img/1990ActIII.jpg",
        artist: "Death Angel",
        country: "Daly City, CA (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1990,
    },
    {
        album: "Void Terra Firma",
        imagePath: "img/1990VoidTerraFirma.jpg",
        artist: "Defiance",
        country: "Oakland, CA (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1990,
    },
    {
        album: "Oppressing The Masses",
        imagePath: "img/1990OppressingTheMasses.jpg",
        artist: "Vio-lence",
        country: "San Francisco, CA (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1990,
    },
    {
        album: "Seasons In The Abyss",
        imagePath: "img/1990SeasonsInTheAbyss.jpg",
        artist: "Slayer",
        country: "Los Angeles, CA (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1990,
    },
    {
        album: "Suiciety",
        imagePath: "img/1990Suiciety.jpg",
        artist: "Realm",
        country: "Milwaukee, WI (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1990,
    },
    {
        album: "Impact Is Imminent",
        imagePath: "img/1990ImpactIsImminent.jpg",
        artist: "Exodus",
        country: "Richmond, CA (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1990,
    },
    {
        album: "Dirty Surfaces",
        imagePath: "img/1990DirtySurfaces.jpg",
        artist: "Risk",
        country: "Witten, West Germany",
        countryPath: "img/FlagGermany.png",
        year: 1990,
    },
    {
        album: "Coma Of Souls",
        imagePath: "img/1990ComaOfSouls.jpg",
        artist: "Kreator",
        country: "Essen, North Rhine-Westphalia, West Germany",
        countryPath: "img/FlagGermany.png",
        year: 1990,
    },
    {
        album: "Insane Society",
        imagePath: "img/1990InsaneSociety.jpg",
        artist: "Wrath",
        country: "Chicago, IL (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1990,
    },
    {
        album: "Souls Of Black",
        imagePath: "img/1990SoulsOfBlack.jpg",
        artist: "Testament",
        country: "Berkeley, CA (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1990,
    },
    {
        album: "Soldiers Of Misfortune",
        imagePath: "img/1990SoldiersOfMisfortune.jpg",
        artist: "Sacrifice",
        country: "Toronto, Ontario (CAN)",
        countryPath: "img/FlagCanada.jpg",
        year: 1990,
    },
    {
        album: "Shock",
        imagePath: "img/1990Shock.jpg",
        artist: "Dogs With Jobs",
        country: "Toronto, Ontario (CAN)",
        countryPath: "img/FlagCanada.jpg",
        year: 1990,
    },
    {
        album: "Cracked Brain",
        imagePath: "img/1990CrackedBrain.jpg",
        artist: "Destruction",
        country: "Weil am Rhein, West Germany",
        countryPath: "img/FlagGermany.png",
        year: 1990,
    },
    {
        album: "Rust In Peace",
        imagePath: "img/1990RustInPeace.jpg",
        artist: "Megadeth",
        country: "Los Angeles, CA (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1990,
    },
    {
        album: "Persistence Of Time",
        imagePath: "img/1990PersistenceOfTime.jpg",
        artist: "Anthrax",
        country: "New York City, NY (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1990,
    },
    {
        album: "Inferior To None",
        imagePath: "img/1990InferiorToNone.jpg",
        artist: "Cyclone",
        country: "Vilvoorde, Belgium",
        countryPath: "img/FlagBelgium.png",
        year: 1990,
    },
    {
        album: "The American Way",
        imagePath: "img/1990TheAmericanWay.jpg",
        artist: "Sacred Reich",
        country: "Phoenix, AZ (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1990,
    },
    {
        album: "By Inheritance",
        imagePath: "img/1990ByInheritance.jpg",
        artist: "Artillery",
        country: "Taastrup, Denmark",
        countryPath: "img/FlagDenmark.png",
        year: 1990,
    },
    {
        album: "For Whose Advantage?",
        imagePath: "img/1990ForWhoseAdvantage.jpg",
        artist: "Xentrix",
        country: "Preston, Lancashire (England)",
        countryPath: "img/FlagEngland.png",
        year: 1990,
    },
    {
        album: "Condemned To Eternity",
        imagePath: "img/1990CondemnedToEternity.png",
        artist: "Re-Animator",
        country: "Hull (England)",
        countryPath: "img/FlagEngland.png",
        year: 1990,
    },
    {
        album: "Two Sides Of A Coin",
        imagePath: "img/1990TwoSidesOfACoin.jpg",
        artist: "Pyracanda",
        country: "Koblenz, West Germany",
        countryPath: "img/FlagGermany.png",
        year: 1990,
    },
    {
        album: "Twisted Into Form",
        imagePath: "img/1990TwistedIntoForm.jpg",
        artist: "Forbidden",
        country: "Hayward, CA (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1990,
    },
    {
        album: "God's Gift",
        imagePath: "img/1990GodsGift.png",
        artist: "Toranaga",
        country: "Bradford (England)",
        countryPath: "img/FlagEngland.png",
        year: 1990,
    },
    {
        album: "Tortured Existence",
        imagePath: "img/1990TorturedExistence.jpg",
        artist: "Demolition Hammer",
        country: "The Bronx, NY (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1990,
    },
    {
        album: "Slaughter In The Vatican",
        imagePath: "img/1990SlaughterInTheVatican.jpg",
        artist: "Exhorder",
        country: "New Orleans, LA (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1990,
    },
    {
        album: "Victims Of Deception",
        imagePath: "img/1991VictimsOfDeception.jpg",
        artist: "Heathen",
        country: "Sonora, CA (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1991,
    },
    {
        album: "Killing In Action",
        imagePath: "img/1991KillingInAction.jpg",
        artist: "Living Death",
        country: "Velbert, West Germany",
        countryPath: "img/FlagGermany.png",
        year: 1991,
    },
    {
        album: "Horrorscope",
        imagePath: "img/1991Horrorscope.jpg",
        artist: "Overkill",
        country: "Old Bridge, NJ (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1991,
    },
    {
        album: "Nothing Is Sacred",
        imagePath: "img/1991NothingIsSacred.jpg",
        artist: "Grinder",
        country: "Frankfurt, West Germany",
        countryPath: "img/FlagGermany.png",
        year: 1991,
    },
    {
        album: "Beyond",
        imagePath: "img/1991Beyond.jpg",
        artist: "Jester's March",
        country: "Dortmund, West Germany",
        countryPath: "img/FlagGermany.png",
        year: 1991,
    },
    {
        album: "Terror Collection",
        imagePath: "img/1991TerrorCollection.jpg",
        artist: "Shah",
        country: "Moscow, Russia",
        countryPath: "img/FlagRussia.png",
        year: 1991,
    },
    {
        album: "Morbid Reality",
        imagePath: "img/1991MorbidReality.jpg",
        artist: "Hexx",
        country: "San Francisco, CA (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1991,
    },
    {
        album: "Play God",
        imagePath: "img/1991PlayGod.jpg",
        artist: "Reverend",
        country: "Seattle, WA (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1991,
    },
    {
        album: "Open Hostility",
        imagePath: "img/1991OpenHostility.jpg",
        artist: "Razor",
        country: "Guelph, Ontario (CAN)",
        countryPath: "img/FlagCanada.jpg",
        year: 1991,
    },
    {
        album: "Behind My Mask",
        imagePath: "img/1991BehindMyMask.jpg",
        artist: "Poltergeist",
        country: "Liestal, Switzerland",
        countryPath: "img/FlagSwitzerland.png",
        year: 1991,
    },
    {
        album: "Stretch Of The Imagination",
        imagePath: "img/1991StretchOfTheImagination.jpg",
        artist: "Taramis",
        country: "Melbourne, Australia",
        countryPath: "img/FlagAustralia.jpg",
        year: 1991,
    },
    {
        album: "Emotional Playground",
        imagePath: "img/1991EmotionalPlayground.jpg",
        artist: "Stone",
        country: "Kerava (Finland)",
        countryPath: "img/FlagFinland.png",
        year: 1991,
    },
    {
        album: "Idolatry",
        imagePath: "img/1991Idolatry.jpg",
        artist: "Devastation",
        country: "Corpus Christi, TX (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1991,
    },
    {
        album: "Drifting In The Sullen Sea",
        imagePath: "img/1991DriftingInTheSullenSea.jpg",
        artist: "Wolf Spider",
        country: "Łódź, Poland",
        countryPath: "img/FlagPoland.jpg",
        year: 1991,
    },
    {
        album: "Hue Of Evil",
        imagePath: "img/1991HueOfEvil.jpg",
        artist: "Wolf Spider",
        country: "Łódź, Poland",
        countryPath: "img/FlagPoland.jpg",
        year: 1991,
    },
    {
        album: "Psycho Savant",
        imagePath: "img/1991PsychoSavant.jpg",
        artist: "Intruder",
        country: "Nashville, TN (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1991,
    },
    {
        album: "Third In Order Of The Sun",
        imagePath: "img/1991ThirdInOrderOfTheSun.jpg",
        artist: "Terrahsphere",
        country: "Nashua, NH (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1991,
    },
    {
        album: "Immortal Entity",
        imagePath: "img/1989ImmortalEntity.jpg",
        artist: "Alligator",
        country: "Vigevano, Italy",
        countryPath: "img/FlagItaly.png",
        year: 1991,
    },
    {
        album: "Probability Of Doom",
        imagePath: "img/1991ProbabilityOfDoom.jpg",
        artist: "Terminator",
        country: "Bzenec, Czech Republic",
        countryPath: "img/FlagCzech.jpg",
        year: 1991,
    },
    {
        album: "3-D",
        imagePath: "img/19913D.png",
        artist: "Wrathchild America",
        country: "Baltimore, MD (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1991,
    },
    {
        album: "Mourning Has Broken",
        imagePath: "img/1991MourningHasBroken.jpg",
        artist: "Sabbat",
        country: "Nottingham (England)",
        countryPath: "img/FlagEngland.png",
        year: 1991,
    },
    {
        album: "Mental Vortex",
        imagePath: "img/1991MentalVortex.jpg",
        artist: "Coroner",
        country: "Zürich, Switzerland",
        countryPath: "img/FlagSwitzerland.png",
        year: 1991,
    },
    {
        album: "Arise",
        imagePath: "img/1991Arise.jpg",
        artist: "Sepultura",
        country: "Belo Horizonte, Brazil",
        countryPath: "img/FlagBrazil.jpg",
        year: 1991,
    },
    {
        album: "Disturbing The Noise",
        imagePath: "img/1991DisturbingTheNoise.jpg",
        artist: "Attomica",
        country: "São José dos Campos, Brazil",
        countryPath: "img/FlagBrazil.jpg",
        year: 1991,
    },
    {
        album: "Balance Of Power",
        imagePath: "img/1991BalanceOfPower.jpg",
        artist: "Arbitrater",
        country: "Warwick (England)",
        countryPath: "img/FlagEngland.png",
        year: 1991,
    },
    {
        album: "The Underworld",
        imagePath: "img/1991TheUnderworld.jpg",
        artist: "Evildead",
        country: "Los Angeles, CA (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1991,
    },
    {
        album: "I Hate Therefore I Am",
        imagePath: "img/1991IHateThereforeIAm.jpg",
        artist: "Cyclone Temple",
        country: "Chicago, IL (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1991,
    },
    {
        album: "As Above, So Below",
        imagePath: "img/1991AsAboveSoBelow.jpg",
        artist: "Forced Entry",
        country: "Seattle, WA (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1991,
    },
    {
        album: "Time Does Not Heal",
        imagePath: "img/1991TimeDoesNotHeal.jpg",
        artist: "Dark Angel",
        country: "Downey, CA (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1991,
    },
    {
        album: "Awakening",
        imagePath: "img/1991Awakening.jpg",
        artist: "Hexenhaus",
        country: "Stockholm, Sweden",
        countryPath: "img/FlagSweden.png",
        year: 1991,
    },
    {
        album: "Meanless Propaganda",
        imagePath: "img/1991MeanlessPropaganda.jpg",
        artist: "Deathblow",
        country: "Tokyo, Japan",
        countryPath: "img/FlagJapan.jpg",
        year: 1991,
    },
    {
        album: "Let Us Not Talk Falsely",
        imagePath: "img/1991LetUsNotTalkFalsely.jpg",
        artist: "LawShed",
        country: "Tokyo, Japan",
        countryPath: "img/FlagJapan.jpg",
        year: 1991,
    },
    {
        album: "Futurity And Human Depressions",
        imagePath: "img/1991FuturityAndHumanDepressions.jpg",
        artist: "Osiris",
        country: "Kampen (Netherlands)",
        countryPath: "img/FlagNetherlands.png",
        year: 1991,
    },
    {
        album: "Nothing's Sacred",
        imagePath: "img/1991NothingsSacred.jpg",
        artist: "Lȧȧz Rockit",
        country: "Oakland, CA (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1991,
    },
    {
        album: "Epidemic Of Violence",
        imagePath: "img/1992EpidemicOfViolence.jpg",
        artist: "Demolition Hammer",
        country: "The Bronx, NY (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1992,
    },
    {
        album: "The Law",
        imagePath: "img/1992TheLaw.jpg",
        artist: "Exhorder",
        country: "New Orleans, LA (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1992,
    },
    {
        album: "Labyrinth Of Problems",
        imagePath: "img/1992LabyrinthOfProblems.jpg",
        artist: "Legion",
        country: "Barcelona, Spain",
        countryPath: "img/FlagSpain.png",
        year: 1992,
    },
    {
        album: "Act",
        imagePath: "img/1992Actjpg",
        artist: "Jester's March",
        country: "Dortmund, West Germany",
        countryPath: "img/FlagGermany.png",
        year: 1992,
    },
    {
        album: "Life Beyond",
        imagePath: "img/1992LifeBeyond.jpg",
        artist: "Deathrow",
        country: "Düsseldorf, West Germany",
        countryPath: "img/FlagGermany.png",
        year: 1992,
    },
    {
        album: "The Truth",
        imagePath: "img/1992TheTruth.jpg",
        artist: "Antidote",
        country: "Helsinki (Finland)",
        countryPath: "img/FlagFinland.png",
        year: 1992,
    },
    {
        album: "The Plot Sickens",
        imagePath: "img/1992ThePlotSickens.jpg",
        artist: "Mystik",
        country: "Cleveland, OH (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1992,
    },
    {
        album: "Thorns",
        imagePath: "img/1992Thorns.jpg",
        artist: "Pyracanda",
        country: "Koblenz, West Germany",
        countryPath: "img/FlagGermany.png",
        year: 1992,
    },
    {
        album: "Brainless World",
        imagePath: "img/1992BrainlessWorld.jpg",
        artist: "Brainless",
        country: "Sennfeld, West Germany",
        countryPath: "img/FlagGermany.png",
        year: 1992,
    },
    {
        album: "One Way",
        imagePath: "img/1992OneWay.jpg",
        artist: "Turbo",
        country: "Poznań, Poland",
        countryPath: "img/FlagPoland.jpg",
        year: 1992,
    },
    {
        album: "Force Of Habit",
        imagePath: "img/1992ForceOfHabit.jpg",
        artist: "Exodus",
        country: "Richmond, CA (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1992,
    },
    {
        album: "Easier To Lie",
        imagePath: "img/1992EasierToLie.jpg",
        artist: "Vulture",
        country: "Rotterdam (Netherlands)",
        countryPath: "img/FlagNetherlands.png",
        year: 1992,
    },
    {
        album: "The Ritual",
        imagePath: "img/1992TheRitual.jpg",
        artist: "Testament",
        country: "Berkeley, CA (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1992,
    },
    {
        album: "The Reborn",
        imagePath: "img/1992TheReborn.jpg",
        artist: "Risk",
        country: "Witten, West Germany",
        countryPath: "img/FlagGermany.png",
        year: 1992,
    },
    {
        album: "Beyond Recognition",
        imagePath: "img/1992BeyondRecognition.jpg",
        artist: "Defiance",
        country: "Oakland, CA (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1992,
    },
    {
        album: "Where Evil Dwells",
        imagePath: "img/1992WhereEvilDwells.jpg",
        artist: "Darklin Reach",
        country: "Chicago, IL (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1992,
    },
    {
        album: "Between Good And Evil",
        imagePath: "img/1992BetweenGoodAndEvil.jpg",
        artist: "Toxic Shock",
        country: "Eislingen, West Germany",
        countryPath: "img/FlagGermany.png",
        year: 1992,
    },
    {
        album: "Stone Cold Sober",
        imagePath: "img/1992StoneColdSober.jpg",
        artist: "Tankard",
        country: "Frankfurt, West Germany",
        countryPath: "img/FlagGermany.png",
        year: 1992,
    },
    {
        album: "Chaos A.D.",
        imagePath: "img/1993ChaosAD.jpg",
        artist: "Sepultura",
        country: "Belo Horizonte, Brazil",
        countryPath: "img/FlagBrazil.jpg",
        year: 1993,
    },
    {
        album: "Darkened Reality",
        imagePath: "img/1993DarkenedReality.jpg",
        artist: "Arbitrater",
        country: "Warwick (England)",
        countryPath: "img/FlagEngland.png",
        year: 1993,
    },
    {
        album: "Кровоизлияние (Extravasation)",
        imagePath: "img/1993Extravasation.png",
        artist: "Аспид (Aspid)",
        country: "Volgodonsk, Russia",
        countryPath: "img/FlagRussia.jpg",
        year: 1993,
    },
    {
        album: "Nothing To Gain",
        imagePath: "img/1993NothingToGain.jpg",
        artist: "Vio-lence",
        country: "San Francisco, CA (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1993,
    },
    {
        album: "Onward Thru The Fog",
        imagePath: "img/1993OnwardThruTheFog.jpg",
        artist: "Leviathen",
        country: "Bath, PA (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1993,
    },
    {
        album: "Rules Of Peace",
        imagePath: "img/1993RulesOfPeace.jpg",
        artist: "Contradiction",
        country: "Wuppertal, West Germany",
        countryPath: "img/FlagGermany.png",
        year: 1993,
    },
    {
        album: "Different",
        imagePath: "img/1993Different.jpg",
        artist: "Crionic",
        country: "Přelouč, Czech Republic",
        countryPath: "img/FlagCzech.jpg",
        year: 1993,
    },
    {
        album: "Apocalypse Inside",
        imagePath: "img/1993ApocalypseInside.jpg",
        artist: "Sacrifice",
        country: "Toronto, Ontario (CAN)",
        countryPath: "img/FlagCanada.jpg",
        year: 1993,
    },
    {
        album: "Kick 'Em Hard",
        imagePath: "img/1993KickEmHard.jpg",
        artist: "Addictive",
        country: "Sydney, Australia",
        countryPath: "img/FlagAustralia.jpg",
        year: 1993,
    },
    {
        album: "Visitör",
        imagePath: "img/1993Visitor.jpg",
        artist: "Visitör",
        country: "Orange County, CA (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1993,
    },
    {
        album: "Something Wicked",
        imagePath: "img/1993SomethingWicked.jpg",
        artist: "Nuclear Assault",
        country: "New York City, NY (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1993,
    },
    {
        album: "Grin",
        imagePath: "img/1993Grin.jpg",
        artist: "Coroner",
        country: "Zürich, Switzerland",
        countryPath: "img/FlagSwitzerland.png",
        year: 1993,
    },
    {
        album: "Will Work For Food",
        imagePath: "img/1993WillWorkForFood.jpg",
        artist: "Unlce Slam",
        country: "Beverly Hills, CA (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1993,
    },
    {
        album: "Nothing Lasts Forever",
        imagePath: "img/1993NothingLastsForever.jpg",
        artist: "Poltergeist",
        country: "Liestal, Switzerland",
        countryPath: "img/FlagSwitzerland.png",
        year: 1993,
    },
    {
        album: "My Friend Lonely",
        imagePath: "img/1994MyFriendLonely.jpg",
        artist: "Cyclone Temple",
        country: "Chicago, IL (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1994,
    },
    {
        album: "King Of The Kill",
        imagePath: "img/1994KingOfTheKill.jpg",
        artist: "Annihilator",
        country: "Ottawa, Ontario (CAN)",
        countryPath: "img/FlagCanada.jpg",
        year: 1994,
    },
    {
        album: "Total",
        imagePath: "img/1994Total.jpg",
        artist: "Antidote",
        country: "Helsinki (Finland)",
        countryPath: "img/FlagFinland.png",
        year: 1994,
    },
    {
        album: "Escape From Mind",
        imagePath: "img/1994EscapeFromMind.jpg",
        artist: "Shah",
        country: "Moscow, Russia",
        countryPath: "img/FlagRussia.png",
        year: 1994,
    },
    {
        album: "P.S.I.H.O.",
        imagePath: "img/1994PSIHO.jpg",
        artist: "Shah",
        country: "Moscow, Russia",
        countryPath: "img/FlagRussia.png",
        year: 1994,
    },
    {
        album: "Iceland",
        imagePath: "img/1994Iceland.jpg",
        artist: "Iceland",
        country: "Plaisir, France",
        countryPath: "img/FlagFrance.png",
        year: 1994,
    },
    {
        album: "When God Dies",
        imagePath: "img/1995WhenGodDies.jpg",
        artist: "Unlce Slam",
        country: "Beverly Hills, CA (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1995,
    },
    {
        album: "Millennium",
        imagePath: "img/1996Millennium.jpg",
        artist: "Agony",
        country: "Bogota (Colombia)",
        countryPath: "img/FlagColombia.png",
        year: 1996,
    },
    {
        album: "Unity",
        imagePath: "img/1997Unity.jpg",
        artist: "Pariah",
        country: "Newcastle (England)",
        countryPath: "img/FlagEngland.png",
        year: 1997,
    },
    {
        album: "Thrashback",
        imagePath: "img/1998Thrashback.jpg",
        artist: "Whiplash",
        country: "Passaic, NJ (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1998,
    },
    {
        album: "Bigger Than The Devil",
        imagePath: "img/1999BiggerThanTheDevil.jpg",
        artist: "S.O.D.",
        country: "New York City, NY (USA)",
        countryPath: "img/FlagUSA.png",
        year: 1999,
    }
];